### PR TITLE
Added ITrackableExtended interface.

### PR DESCRIPTION
**Pull request by luboshl**
Created on the basis of issue **#105: ITrackableExtended&lt;TProperty&gt; interface**

### CODE REVIEW

**Comment by luboshl** [comment]
I fixed commits to have only one, so I closed previous PL #108.

**Comment by tonysneed** [comment]
Regarding our workflow, you don't have to submit a single commit until I am ready to merge the PR.  So you can have as many commits as you want when you submit your PR.  And if I suggest changes, there will be even more commits.  So that is why we wait until the review is complete, with all the changes implemented, until I ask you to do a **squash commit** and a `git push -f`.

**Comment by tonysneed** [comment]
I'll mention here that our workflow is based on this guide: http://blogs.msdn.com/b/cdndevs/archive/2016/01/06/submitting-your-first-pull-request.aspx.

**Comment by luboshl** [comment]
Yes, I understand now. There was a mishmash in commits, because I made changes directly to `develop` branch, and there were also commits with App.config changes (from the other PR). Then I tried to reverse them - and ups, there were other changes :smile: So I createt brand new branch and tried to do it clean. For the first time I haven't noticed that there is also list of files and changes during PR.

I understand now what swuash commit is, but I have never done it before. I hope I haven't make a bigger mess... Git / GitHub is completely new for me, but I realy love it just from the first moment (from this friday :smile: )

**Comment by luboshl** [comment]
And yes, I have read the guide you've referenced. And some others :) I need to get used this workflow and new environment. I've used TFS for a long time.

**Comment by tonysneed** [comment]
@luboshl, Welcome to the world of Git and GitHub!  I also spent many years in TFS, but now that I am using Git, I can't imagine going back. :smile:

**Comment by tonysneed** [comment]
@luboshl, Congrats on your 2nd merged PR! Hopefully there are many more to come. :triumph:

**Comment by tonysneed** [comment]
I also pushed a small change to TrackableEntities.Common.Extended in which I added an xml doc section to the csproj file for debug and release build configs.

**Comment by luboshl** [comment]
:smile:

**Pull request merged**
