### PR TITLE
Added ITrackableExtended interface.

### PR DESCRIPTION
**Pull request by luboshl**
Created on the basis of **#105: ITrackableExtended&lt;TProperty&gt; interface**

### CODE REVIEW

**Comment by luboshl** [comment]
Wow, that is not what I expected :( I created new local branch "extended-states", in its history i can see only one commit: https://github.com/luboshl/trackable-entities/commit/a5553d4216b2b910079340129a0ddd780da6c24c, but here I can see more commits including reverts... :(

I think final changes are what it should be, but I haven't expected other commits. You can reject this PL and I can try to do it better :disappointed:

**Comment by tonysneed** [comment]
I'll have a look at this -- thank you!

**Comment by tonysneed** [comment]
No worries - after I review it, I'll have you do a squash commit, so it will be just one commit in the end.

**Comment by luboshl** [comment]
I've created ne PR #110.

**Pull request closed without merging**
