### PR TITLE
Fixed LoadRelatedEntities

### PR DESCRIPTION
**Pull request by weitzhandler**
By skipping complex types.
#177

### CODE REVIEW

**Comment by weitzhandler** [comment]
Are the myget feeds automatically updated now? Because the error still persists on CI00038.

**Comment by weitzhandler** [comment]
Are the myget feeds automatically updated now? Because the error still persists on CI00038.
Unless there is an additional issue which this repo hasn't targeted 🤒

**Comment by weitzhandler** [comment]
Apparently I'm still getting the error reported in #177 in CI00040.

> NullReferenceException: 
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
>    at TrackableEntities.EF6.DbContextExtensions.IdMatcher.GetKeyValue(Object entity)
>    at TrackableEntities.EF6.DbContextExtensions.IdMatcher.System.Collections.Generic.IEqualityComparer<System.Object>.GetHashCode(Object obj)
>    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
>    at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
>    at TrackableEntities.Common.ObjectVisitationHelper.IsVisited(Object obj)
>    at TrackableEntities.Common.ObjectVisitationHelper.TryVisit(Object obj)
>    at TrackableEntities.EF6.DbContextExtensions.<LoadRelatedEntitiesAsync>d__2d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

Why is that happening? Does the CI40 have the latest commits?

**Comment by tonysneed** [comment]
PR #182 is in this build.

**Comment by tonysneed** [comment]
You can debug it with DotPeek.

**Comment by tonysneed** [comment]
http://trackableentities.github.io/5-debugging.html

**Comment by weitzhandler** [comment]
LOL I know, didn't take the time to right one...

**Comment by weitzhandler** [comment]
Here's the code from DotPeek:

    private static void LoadRelatedEntities(this DbContext context, IEnumerable<ITrackable> items, ITrackable parent, ObjectVisitationHelper visitationHelper, bool loadAll)
    {
      if (items == null)
        return;
      IEnumerable<object> objects = (loadAll ? (IEnumerable) items : (IEnumerable) items.Where<ITrackable>((Func<ITrackable, bool>) (t => t.get_TrackingState() == 1 || parent != null && parent.get_TrackingState() == 1))).Cast<object>().Where<object>((Func<object, bool>) (i => !context.IsComplexType(i.GetType()) && !visitationHelper.IsVisited(i)));
      foreach (PropertyInfo referenceProperty in objects.SelectMany((Func<object, IEnumerable<PropertyInfo>>) (entity => (IEnumerable<PropertyInfo>) entity.GetType().GetProperties()), (entity, prop) =>
      {
        var data = new{ entity = entity, prop = prop };
        return data;
      }).Where(param0 => typeof (ITrackable).IsAssignableFrom(param0.prop.PropertyType)).Select(param0 => param0.prop).Distinct<PropertyInfo>())
      {
        string name = referenceProperty.Name;
        Type propertyType = referenceProperty.PropertyType;
        IEnumerable<object> relatedEntities1 = (IEnumerable<object>) context.GetRelatedEntities(objects, referenceProperty.DeclaringType, name, propertyType);
        if (relatedEntities1.Any<object>())
        {
          IEnumerable<object> relatedEntities2 = relatedEntities1.Select<object, object>((Func<object, object>) (e => visitationHelper.FindVisited(e) ?? e));
          context.SetRelatedEntities(objects, relatedEntities2, referenceProperty, referenceProperty.DeclaringType, name, propertyType);
        }
      }
      using (IEnumerator<ITrackable> enumerator = items.GetEnumerator())
      {
        while (((IEnumerator) enumerator).MoveNext())
        {
          ITrackable current = enumerator.Current;
          if (visitationHelper.TryVisit((object) current))
          {
            bool loadAll1 = loadAll || current.get_TrackingState() == 1 || parent != null && parent.get_TrackingState() == 1;
            context.LoadRelatedEntitiesOnProperties(current, visitationHelper, loadAll1);
          }
        }
      }
    }

So looks like my code is there, I believe I should add a test.

**Comment by weitzhandler** [comment]
Really it would be a bit hard for me now to create a repro test, but I think I found the issue, in `DbContextExtensions` line [395](https://github.com/trackableentities/trackable-entities/blob/develop/Source/TrackableEntities.EF.5/DbContextExtensions.cs#L395), we also need to exit the  iterator if the current entity is a complex type, and this just makes sense because a CT cannot have any related entities to load either.

**Comment by weitzhandler** [comment]
@tonysneed 
Really it would be a bit hard for me now to create a repro test, but I think I found the issue, in `DbContextExtensions` line [395](https://github.com/trackableentities/trackable-entities/blob/develop/Source/TrackableEntities.EF.5/DbContextExtensions.cs#L395), we also need to exit the  iterator if the current entity is a complex type, and this just makes sense because a CT cannot have any related entities to load either.'
I'm going to commit this into the [complex-types](https://github.com/weitzhandler/trackable-entities/tree/complex-types) branch and PR.

**Comment by weitzhandler** [comment]
Addressed by #185 with conflicts against #170.

**Comment by weitzhandler** [comment]
Addressed by #191.

**Pull request merged**
