### PR TITLE
Added configuration parameters for LocalDB in test projects.

### PR DESCRIPTION
**Pull request by luboshl**
I added *commented* configuration parameters for EntityFramework to be able to use LocalDB. Developer has to uncomment this new section and comment section for SQL Express (or Full) to run tests.

### CODE REVIEW

**Comment by luboshl** [comment]
I fixed commits to have only one, so I closed previous PL #104 and #107.

**Comment by luboshl** [comment]
*Oh happy day, oh happy day...*

My first accepted PR :rocket:

**Comment by tonysneed** [comment]
Congrats @luboshl!  You can pull the latest from the *develop* branch. I corrected the csproj file and deleted the project.json file.

**Comment by luboshl** [comment]
Ok, thanks, Tony

**Pull request merged**
