### PR TITLE
FIX: Deleting one-to-one relationships #122

### PR DESCRIPTION
**Pull request by azabluda**
My proposal for issue #122

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks @azabluda! Great job as always. :smile:

**Comment by cyrusdowney** [comment]
Thanks @azabluda!  

@azabluda and @tonysneed,

I have a question concerning the overall process.  When do changes typically hit nuget?  I hopped back onto this issue and was going to update our projects nuget packages, and realized that this fix was not pushed out yet.

**Comment by tonysneed** [comment]
You can get the latest NuGet package with the fix included by configuring your NuGet settings to point to the MyGet feed. We have support for continuous integration, so you don't have to wait for an official release on nuget.org.

**Comment by tonysneed** [comment]
For info on the TE MyGet feed, see this blog post: http://blog.tonysneed.com/2014/10/25/myget-continuous-integration-for-the-rest-of-us/

**Comment by cyrusdowney** [comment]
Awesome - that worked great.  The only issue I ran into was for me the pdb files for the TrackableEntities.Common.dll was missing.  I ended up generating the pdf files for that dll using telerik just decomplie.

**Comment by tonysneed** [comment]
@cyrusdowney, I now recommend generating your own PDB's, because I found symbolsource.org to be unreliable.  See http://trackableentities.github.io/5-debugging.html.

**Comment by cyrusdowney** [comment]
Ok thanks.

**Pull request merged**
