### PR TITLE
Added SQL connection parameters for LocalDB to App.config(s) for EF5 and EF6 Tests.

### PR DESCRIPTION
**Pull request by luboshl**
I added *commented* connection parameters for EntityFramework to be able to use LocalDB. Developer has to uncomment this new section and comment section for SQL Express (or Full) to run tests.

### CODE REVIEW

**Comment by luboshl** [comment]
Now I know that I did it wrong, because I made both commits straight to *develop* branch. If I understandu it now, I should have done another branch just for these changes. Sorry, committing to github is new for me :smile:

**Comment by tonysneed** [comment]
See if you can create a local branch for this PR, merge your commits into that local branch, then push to create another PR.  Let's do it right. :smile:

**Comment by luboshl** [comment]
I was not able (= I don't know how :smirk:) to create local branch for this PR. So I created new local branch from *develop* branch, but from history, before my two commits. So I had clean branch. There I made changes in app.config(s) again. This process is not certainly the best, but I haven't found better... Next time I know that I have to create ne branch immediately :smile:

**Comment by tonysneed** [comment]
Great, you can publish the new branch and then create a new PR. I will close the other PR.

**Pull request closed without merging**
