### PR TITLE
Created DbContext.ApplyChanges overloads accepting lambda

### PR DESCRIPTION
**Pull request by luboshl**
Based on  #106

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks @luboshl for the PR.  I'm having a look at it now.

I can see an issue with the method signature for the new overload of `ApplyChanges`, which explains why you were having to cast `e` as you mentioned in your [comment](https://github.com/TrackableEntities/trackable-entities/issues/106#issuecomment-172392574).

I will start with comments on your first commit: 1fc8527ed69b15ceb5de1899882c8ac820a1dff7. Heading over to do that now.

**Comment by tonysneed** [comment]
By the way, I am located in Europe, which is GMT +1.  So I am now starting my day.  Where are you physically located?

It is also possible for us to chat in real time.  I created a chat room for this repo on [gitter](https://gitter.im).  Let me know if you are able to join.

**Comment by luboshl** [comment]
Yes, exactly. But it's question, if it is better to have two or more collback (each for different type) or to have only one and if I need to use it for different types, then I have to cast it:
```C#
context.ApplyChanges<ITrackable>(order, (e, rt) =>
{
    var orderEntity = e as Order;
    var orderDetailEntity = e as OrderDetail;

    if (orderEntity != null)
        return ...

    if (orderDetailEntity != null)
        return ...
}
```

**Comment by luboshl** [comment]
But you are not able to do this:
```C#
public static void ApplyChanges<TEntity>(this DbContext context, ITrackable item,
    params Func<TEntity, RelationshipType, EntityState?>[] stateSelector)
```
because you have only one `TEntity` (for example `Order`), but you want to have two callback - for `Order` and for `OrderDetail` as input argument in the callback function
In this case you still need to set `TEntity` to `ITrackable` (or to any base class, if exists) an then cast it to concrete type.

**Comment by tonysneed** [comment]
This PR is looking good so far.  We may need to add a couple more tests.

But then we should be able to implement the two new `ApplyChanges` overloads.  We will need to add a `stateSelector` parameter to the private `ApplyChanges` method as an optional parameter defaulting to `null`.  If it is not null, we invoke it, then if it does not return null, we set the entity state to whatever is returned.

**Comment by luboshl** [comment]
I expected we will create more test. Different relationships and combinations of states...

I think we should add `IList<IInterceptor>` collection, one we have created this interface and method `AddInterceptor` :) But it is true, that it is not absolutely necessary. We have only one implementation of `IInterceptor` so we can add its `stateSelector` directly. In the future, if we add some more, only internal implementation (I mean private `ApplyChanges` method) will change. Still if we want to use `stateSelector` directly, we have to put collection of them.

**Comment by tonysneed** [comment]
Yes, we will probably need to refactor the private `ApplyChanges` method when we implement #114.  But for this PR, we can go ahead and just add an optional `stateSelector` parameter to the private `ApplyChanges` method.  Then when we go to implement #114, we can [refactor](https://en.wikipedia.org/wiki/Test-driven_development#5._Refactor_code).  Because of the complexity of change tracking, I've found it beneficial to adopt a TDD mentality. :smile:

**Comment by luboshl** [comment]
I meant we **are** in the other PR (#114) and that this (#111) is deprecated :)

**Comment by tonysneed** [comment]
Ah, I see now that you merged your 105 branch into the 106 branch.  So we can close this PR and proceed with #114.  That will make it easier.

I'm now looking at that PR and I can make commits on your commits there.

**Pull request closed without merging**
